In [1]:
!python models.py

theta:
 [-25.14941364   0.20613637   0.20137516] 

Expected theta (approx):
 -25.161 0.206 0.201



In [2]:
import numpy as np
import scipy.io
import scipy.optimize 
from models import LogisticRegression

data = np.genfromtxt('ex2data1.txt', delimiter=',')
X = data[:, :2]
y = data[:, 2]

# run the model
theta = LogisticRegression(X, y)
# print theta to screen
print('theta:')
print(' %s \n' % theta)
print('Expected theta (approx):')
print(' -25.161 0.206 0.201\n')

theta:
 [-25.14941364   0.20613637   0.20137516] 

Expected theta (approx):
 -25.161 0.206 0.201



In [7]:
from sklearn.linear_model import LogisticRegression as LR
model = LR(solver='lbfgs')
model.fit(X, y)
model.intercept_, model.coef_

(array([-25.05219314]), array([[0.20535491, 0.2005838 ]]))