In [1]:
import numpy as np

In [5]:
x = np.array([3, 5])
z = np.array([[6, 8, 4], [4, 6, 12]])
x.shape, z.shape

((2,), (2, 3))

In [6]:
np.matmul(x, z)

array([38, 54, 72])

In [7]:
np.dot(x, z)

array([38, 54, 72])

In [8]:
x.dot(z)

array([38, 54, 72])

In [12]:
def operations(h, w):
    """
    Takes two inputs, h and w, and makes two Numpy arrays A and B of size
    h x w, and returns A, B, and s, the sum of A and B.

    Arg:
      h - an integer describing the height of A and B
      w - an integer describing the width of A and B
    Returns (in this order):
      A - a randomly-generated h x w Numpy array.
      B - a randomly-generated h x w Numpy array.
      s - the sum of A and B.
    """
    #Your code here
    A = np.random.random((h, w))
    B = np.random.random((h, w))
    s = A + B
    return A, B, s


In [13]:
operations(2, 3)

(array([[0.93009   , 0.72951275, 0.73103429],
        [0.49527561, 0.27677302, 0.89120346]]),
 array([[0.46866637, 0.60024047, 0.47151281],
        [0.68643648, 0.83436823, 0.74369265]]),
 array([[1.39875637, 1.32975322, 1.2025471 ],
        [1.18171208, 1.11114125, 1.63489611]]))

In [18]:
def norm(A, B):
    """
    Takes two Numpy column arrays, A and B, and returns the L2 norm of their
    sum.

    Arg:
      A - a Numpy array
      B - a Numpy array
    Returns:
      s - the L2 norm of A+B.
    """
    #Your code here
    return np.linalg.norm(A + B)

In [19]:
np.linalg.norm(x)

5.830951894845301

In [1]:
! python ./project0/debug.py

3
6
9
15
3
6
9


In [51]:
predictions = 0
metrics = [(lambda i: lambda x: x + i)(i) for i in range(3)]

sum_metrics = 0
for metric in metrics:
    sum_metrics += metric(predictions)

In [52]:
sum_metrics

3

In [43]:
eval(str(i))

2

In [55]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

In [3]:
def defaulttrap(d, m=[]):
    m.append(d)
    return m

In [4]:
defaulttrap(1)

[1]

In [5]:
defaulttrap(2)

[1, 2]

In [6]:
defaulttrap(2, [])

[2]

In [7]:
defaulttrap(3)

[1, 2, 3]